# Generated by Django 4.1.1 on 2022-09-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBike', models.IntegerField()),
                ('Name', models.TextField()),
                ('Price', models.IntegerField()),
                ('Description', models.TextField()),
                ('Instock', models.BooleanField()),
            ],
        ),
    ]
