# Generated by Django 4.1.1 on 2022-09-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPS_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='Name',
            new_name='name',
        ),
    ]
