# Generated by Django 4.1.1 on 2022-09-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPS_App', '0002_rename_name_bikes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='idBike',
        ),
    ]
